CREATE TABLE IF NOT EXISTS MEMBER(
    SEQ  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID CHARACTER VARYING(200) NOT NULL,
    PASSWORD CHARACTER VARYING(200) NOT NULL,
    NAME CHARACTER VARYING(200) NOT NULL,
    AUTHORITY CHARACTER VARYING(200) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS ARTICLE(
    SEQ INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE CHARACTER VARYING(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL ,
    UPDATE_TIME TIMESTAMP NOT NULL ,
    VISIBLEw INT NOT NULL ,
    VIEWS INT NOT NULL ,
    LIKES INT NOT NULL
    );
