CREATE TABLE IF NOT EXISTS MEMBER(
    SEQ  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID CHARACTER VARYING(200) NOT NULL,
    PASSWORD CHARACTER VARYING(200) NOT NULL,
    NAME CHARACTER VARYING(200) NOT NULL,
    AUTHORITY CHARACTER VARYING(200) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP NOT NULL
    );
