
CREATE TABLE IF NOT EXISTS ARTICLE
(
    ID          INT            NOT NULL ,
    TITLE       VARBINARY(150) NOT NULL,
    AUTHOR      VARBINARY(200) NOT NULL,
    LIKES       INT            NOT NULL,
    CONTENT     VARBINARY(200) NOT NULL,
    CREATE_TIME TIMESTAMP      NOT NULL,
    UPDATE_TIME TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBER(
    SEQ INT NOT NULL  AUTO_INCREMENT,
    ID VARCHAR(200) NOT NULL ,
    NAME VARCHAR(200) NOT NULL ,
    PASSWORD VARCHAR(500) NOT NULL ,
    CREATE_TIME TIMESTAMP NOT NULL ,
    UPDATE_TIME TIMESTAMP NOT NULL ,
    AUTHORITY VARCHAR(200) NOT NULL
)